name: Update Data

on:
  schedule:
    - cron: '*/30 6-23 * * *' # Every 30 minutes from 6 to midnight
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt install -y jq

      - name: Get data
        run: curl https://recsports.osu.edu/fms/Home/GetLocations?locationCode=rpac | jq .locations[] | jq '.locationName, .lastCount'

