name: Update Data

on:
  schedule:
    # Shifted back 5 because workflows are on utc-0 and Ohio State is utc-5
    - cron: '*/30 1-18 * * *' # Every 30 minutes from 6 to midnight EST
    - cron: '5 19 * * *' # Every day at 5 after midnight EST
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get data
        if: github.event.schedule == '*/30 1-18 * * *'
        run: python update.py
      
      - name: Update day
        if: github.event.schedule == '5 19 * * *'
        run: python update.py daily
        
      - name: Git commit
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "Update data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
