name: Update Data

on:
  schedule:
    # Shifted up 5 because workflows are on utc-0 and Ohio State is utc-5
    # Every 30 minutes from 6am to midnight EST
    - cron: '*/30 11-23 * * *'
    - cron: '*/30 0-5 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: intraday # work on intraday branch

      - name: Git pull
        run: git pull

      - name: Get data
        run: python update.py

      - name: Git commit
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -am "Update data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
