name: Update Data

on:
  schedule:
    - cron: '*/30 6 * * *' # Every 30 minutes from 6 to midnight
    - cron: '5 0 * * *' # Every day at 5 after midnight
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt install -y jq

      - name: Get data
        if: github.event.schedule == '*/30 6 * * *'
        run: python update.py
      
      - name: Update day
        if: github.event.schedule == '5 0 * * *'
        run: python update.py daily
        
      - name: Git commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit -am "Update data"
          git push origin main
